# Generated by Django 3.1 on 2020-12-25 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201225_0304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='staff_name',
            new_name='name',
        ),
    ]
