# Generated by Django 3.1 on 2020-12-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201225_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='category',
            field=models.CharField(choices=[('IT DEPT.', 'HR DEPT.'), ('HR DEPT.', 'IT DEPT.'), ('FINANCE', 'AUDIT'), ('MARKETING', 'SALES')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='utility',
            name='status',
            field=models.CharField(choices=[('IsActive', 'IsNotActive'), ('IsNotActive', 'IsActive')], max_length=100, null=True),
        ),
    ]
